Netflix/Hystrix

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java

Thread completion events (metrics and hook execution) were firing earlier in 1.4.x, as documented by #377, and discovered via #327.  This PR moves them back to the rightful place at the end of the Observable chain.  Along the way, 2 unrelated bugs were fixed.
1) ```Hystrix.startCurrentThreadExecutingCommand()``` and the corresponding end ```Action0``` were being invoked twice per command.  Now they both invoked once
2) As documented in #448, ```HystrixCommand.isExecutedInThread()``` was documented to only return true when it actually ran in the Hystrix thread.  In practice, it was returning true in the case that it was set up to run in a thread, but got rejected.  Fixing this made the implementation of the thread completion straightforward.

Move thread completion to end of chain

---

hystrix-core/src/main/java/com/netflix/hystrix/Hystrix.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/properties/HystrixPropertiesFactory.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixTest.java

Resettable command and thread pool defaults

---

hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java

Add more unit tests for HystrixRequestLog to HystrixObservableCommandTest

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java

Hi,
recently introduced Hystrix into an existing codebase and like it a lot. That codebase uses a custom `BusinessException` to signal bad user input etc. We would like to automatically wrap the `BusinessException`s into a `HystrixBadRequestException` to isolate Hystrix-Exception handling and not having to touch all the existing code.
However, turning an `Exception` into a `HystrixBadRequestException` inside `HystrixCommandExecutionHook#onRunError` did not side-step the fallback machinery. This pull request fixes that.
Cheers,
Gerrit

Bypass fallback/circuit breaker for BadRequestExceptions from ExecutionHook

---

hystrix-core/src/main/java/com/netflix/hystrix/Hystrix.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/HystrixPlugins.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/metrics/HystrixMetricsPublisherFactory.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixThreadPoolTest.java
hystrix-core/src/test/java/com/netflix/hystrix/strategy/HystrixPluginsTest.java
hystrix-core/src/test/java/com/netflix/hystrix/strategy/metrics/HystrixMetricsPublisherFactoryTest.java

Fixing the resettability of HystrixMetricsPublisherFactory

---

hystrix-contrib/hystrix-clj/src/main/clojure/com/netflix/hystrix/core.clj
hystrix-contrib/hystrix-clj/src/test/clojure/com/netflix/hystrix/core_test.clj

* s/toBlockingObservable/toBlocking
* Changed implementation of observe-later-on to use Observable.observeOn

Fixed Clojure unit tests that failed with RxJava 1.0 (Backport from master)

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/exception/HystrixRuntimeException.java

This is an updated version of #506.  It adds assertions on hook execution.

Backport of #327

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/Hystrix.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixObservableCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixTest.java

Uncovered Issue #510 during this investigation.  Will update this PR once that is resolved.

Matching hook orders from 1.3.x

---

hystrix-core/src/main/java/com/netflix/hystrix/strategy/executionhook/HystrixCommandExecutionHook.java

onRunSuccess and onThreadCompelte hooks get invoked even if calling thread times out.

Added Javadoc after clarifying #510.  When a Hystrix thread executes,

---

hystrix-contrib/hystrix-servo-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisher.java

Noticed that singleton initialization is not great when debugging an application using this project.  Don't know if it will fix the problem we're seeing, but this initialization is more robust than what was there before.

Updated HystrixServoMetricsPublisher initalization of singleton

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommand.java

For addressing #509, I added comprehensive (I *think*) tests of all execution flows and what hooks get invoked on each.  Out of this, I discovered #513, #514, #515, which will get addressed in separate PRs.
I will also be porting this test suite to master next, and hopefully uncovering the actual issue in #509 that I'm looking for.

Add comprehensive hook tests

---

hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/CommonUtils.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/spring/collapser/CollapserTest.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/spring/command/CommandTest.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/spring/error/ErrorPropagationTest.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/spring/fallback/CommandFallbackTest.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/spring/observable/ObservableTest.java
hystrix-examples/src/main/java/com/netflix/hystrix/examples/basic/CommandCollapserGetValueForKey.java
hystrix-examples/src/main/java/com/netflix/hystrix/examples/basic/CommandWithFallbackViaNetwork.java

The calls to the deprecated getExecutedCommands() from HystrixRequestLog have been updated to getAllExecutedCommands(). This method returns a HystrixInvokableInfo instead of a HystrixCommand, so a few tests and examples have been updated to reflect this changed type as well.

Change calls from getExecutedCommands() to getAllExecutedCommands()

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/TestableExecutionHook.java

A set of comprehensive unit tests around execution hooks for HystrixCommand and HystrixObservableCommand

Port of #520 to master

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java

This allows ```onError()``` hook to always receive a non-null ```Exception```.
Fixes #513 for master

Creating a synthetic exception in the semaphore execution and short-circuited case

---

hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsStreamServlet.java

fixes https://github.com/Netflix/Hystrix/issues/346
WebSphere won't shutdown a servlet until after a 60 second timeout if there is an  instance of the servlet executing a request.  Add a shutdown method to enable a hook to notify Hystrix to shutdown.  You must invoke this method at app server shutdown, perhaps from another servlet's destroy() method.
Also added explicit checkError() in poller loop to detect disconnected client.

Add shutdown hook for WebSphere and checkError() to detect disconnected client

---

hystrix-contrib/hystrix-codahale-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisherCommand.java

Currently all commands are published to CodaHale metrics under the same, hard-coded group name `"HystrixCommand"`. Even if I have multiple groups and many commands within them, all commands appear flat under the same name. This PR fixes it by using *real* group name and building correct metrics hierarchy.

Hard-coded group name when publishing CodaHale metrics fixed

---

hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java

Finishes off #526, now that the synchronous timeout mechanism is removed (#579)

Add nonblocking HystrixCommandTest.queue() unit tests back

---

hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixContextScheduler.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixThreadPoolTest.java
hystrix-core/src/test/java/com/netflix/hystrix/strategy/concurrency/HystrixContextSchedulerTest.java

Fixed issue in #354 by making ```HystrixContextScheduler``` conform with RxJava's Worker contract. See also #593.
To avoid code duplication, it uses the ```rx.internal.schedulers.ScheduledAction```. I don't know how close Hystrix follows RxJava releases, but I'll make steps to have ```ScheduledAction``` part of the stable RxJava API eventually.

Fixed HystrixContextScheduler to conform with RxJava Worker contract

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixObservableCollapser.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCollapserTest.java

Added metrics to HystrixObservableCollapser

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java

Adds more thorough tests as specified by #525, and fixes synchronous exception handling that was missing and caught by these tests

Both sync and async exceptions for hystrix observable cmd

---

hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java

Deflaked HystrixObservableCommandTest.testRejectedViaSemaphoreIsolation

---

hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/spring/fallback/CommandFallbackTest.java
hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPool.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixContextScheduler.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java

Addresses #354 and #598.  I think this causes some Javanica unit tests to fail.  Will address those next

Tie command property to thread interrupt

---

hystrix-contrib/hystrix-codahale-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisherCommand.java
hystrix-contrib/hystrix-javanica/README.md
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/spring/configuration/command/CommandPropertiesTest.java
hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsPoller.java
hystrix-contrib/hystrix-rx-netty-metrics-stream/src/main/java/com/netflix/hystrix/contrib/rxnetty/metricsstream/JsonMappers.java
hystrix-contrib/hystrix-servo-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisherCommand.java
hystrix-contrib/hystrix-yammer-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/yammermetricspublisher/HystrixYammerMetricsPublisherCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandProperties.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandPropertiesTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixTest.java
hystrix-dashboard/src/main/webapp/components/hystrixCommand/hystrixCommand.js

Also deprecate usages of thread-specific setting (like execution.thread.isolation.timeoutInMilliseconds).
This addresses #300

Favor timeout property that is not thread-specific. (execution.timeoutInMilliseconds)

---

hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java

Added unit tests to demonstrate a non-blocking semaphore timeout

---

hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/spring/fallback/CommandFallbackTest.java
hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPool.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixContextScheduler.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java

This is a fix for #663 and #670

Thread interrupt only on timeout

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java

In both unit tests, the InterruptedException is caused by an unsubscription, which in turn is caused by the OnErrorResumeNext operator.

Unit tests demonstrating problems with thread interruptions

---

hystrix-contrib/hystrix-codahale-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisherCommand.java
hystrix-contrib/hystrix-javanica/README.md
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/spring/configuration/command/CommandPropertiesTest.java
hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsPoller.java
hystrix-contrib/hystrix-rx-netty-metrics-stream/src/main/java/com/netflix/hystrix/contrib/rxnetty/metricsstream/JsonMappers.java
hystrix-contrib/hystrix-servo-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisherCommand.java
hystrix-contrib/hystrix-yammer-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/yammermetricspublisher/HystrixYammerMetricsPublisherCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandProperties.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCollapserTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandPropertiesTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTimeoutConcurrencyTesting.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCollapserTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixTest.java
hystrix-core/src/test/java/com/netflix/hystrix/strategy/concurrency/HystrixConcurrencyStrategyTest.java
hystrix-dashboard/src/main/webapp/components/hystrixCommand/hystrixCommand.js
hystrix-examples/src/main/java/com/netflix/hystrix/examples/basic/CommandFacadeWithPrimarySecondary.java
hystrix-examples/src/main/java/com/netflix/hystrix/examples/demo/CreditCardCommand.java

Revert #664 in favor of a similar approach which does not attempt to migrate the property name.

Revert timeout property name change

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/executionhook/HystrixCommandExecutionHook.java
hystrix-core/src/test/java/com/netflix/hystrix/AbstractTestHystrixCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/CommonHystrixCommandTests.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCollapserTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandMetricsTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCollapserTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/InspectableBuilder.java
hystrix-core/src/test/java/com/netflix/hystrix/TestHystrixCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/TestHystrixObservableCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/TestableExecutionHook.java

Addresses #682 and #600 . See #682 for detail on new API.
Since this affects both ```HystrixCommand``` and ```HystrixObservableCommand``` and had a large impact on unit tests, I took some time to share code between the two.  This partially addresses #581

Changes to hook API to make it more Observable-friendly

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/CommonHystrixCommandTests.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java

Found (and fixed) metrics issue where a fallback rejection was counted as both a FALLBACK_REJECTION and FALLBACK_FAILURE.  Now it counts as only a FALLBACK_REJECTION.
Written to help understand #685

Added unit test for fallback rejection

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixContextScheduler.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java

Also added unit test to help with understanding #685

Missing execution event for FALLBACK_REJECTION

---

hystrix-dashboard/src/main/webapp/components/hystrixCommand/hystrixCommand.js

This fixes #709, correcting the mistake introduced by https://github.com/Netflix/Hystrix/commit/dc3bc3cac5ff349cb7cdca93c3bbf0b875f473f7, where "isNaN" is incorrectly cased as "isNan", causing the JavaScript error "isNan is not defined".

This fixes #709: JS error: "isNan is not defined"

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommand.java

Make HystrixCommand.execute()/queue() and AbstractCommand.observe()/toObservable() nonfinal

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/strategy/concurrency/HystrixConcurrencyStrategyTest.java

In https://github.com/Netflix/Hystrix/commit/706a0f267ed65a215de1d813598c6c72b00f76eb,
the guard to initialize the request log based on the property was removed. This
causes a dependency on hystrix context initialization for all custom concurrency
strategies.
Here we add that back in, along with a test to ensure that a custom strategy could
still run without an initialized context.
This PR supercedes https://github.com/Netflix/Hystrix/pull/718/
/cc @mattrjacobs

Check if the request log is enabled before requiring the context is initialized.

---

hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java

Up the time before failure in HystrixCommandTest.testFallbackRejectionOccursWithLatentFallback

---

hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/utils/AopUtils.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/spring/command/CommandTest.java

The HystrixCommandAspect fails with NPE if the method annotated with @HystrixCommand is implemented in a superclass. Since the Class#getDeclaredMethod can't see inherited methods but in spite of Class#getMethod can see private ones, I performed a recursive search up by class hierarchy.

fixed AopUtils#getDeclaredMethod to look for method also in superclasses

---

hystrix-dashboard/src/main/java/com/netflix/hystrix/dashboard/stream/ProxyStreamServlet.java

When running the hystrix-dashboard on Tomcat with apache in front using AJP/mod_JK, we could not get the streams (from either hystrix directly, or through Turbine) working. In the Chrome JS-console there were errors mentioning the chunked response from proxy.stream was in error. 
curling a bit showed this: 
curl -iv --raw http://dev.dashboard.finn.no/hystrix-dashboard/proxy.stream?origin=dev-api1.finntech.no/iad/hystrix.stream
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Wed, 11 Feb 2015 13:57:03 GMT
Date: Wed, 11 Feb 2015 13:57:03 GMT
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: …

Don't pass on the Transfer-Encoding header when streaming

---

hystrix-core/src/main/java/com/netflix/hystrix/strategy/HystrixPlugins.java

> **Use Archaius for Hystrix plugin setup**
>
> Currently, Hystrix lets you define custom strategies in two ways:
> 1) with System properties
> 2) with bootstrapping via HystrixPlugins.getInstance().registerXXX
> If neither is specified, the default strategy is used.
> 
> This change replaces hardwired System.getProperty calls with lookup
> via Archaius. So one can override the plugin strategies used with
> any configuration provider Archaius is configured with.
> 
> Most importantly, it has the effect of checking any file called
> "config.properties" on the classpath as well as using system properties.
> This lets you configure plugin strategies without having to write
> Java code for it, or having to run the application with additional
> system properties.
> 
> Fixes #92
According to …

Use Archaius for Hystrix plugin setup

---

hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsPoller.java

Filter out thread pools from metrics stream that have had no commands executed on them

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandProperties.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandPropertiesTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java

Add ability to disable timeout per-command and wire it in

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixCircuitBreaker.java

Fix return value of HystrixCircuitBreakerImpl.isOpen when we lose the race to open a circuit

---

build.gradle
hystrix-core/build.gradle
hystrix-core/src/jmh/java/com/netflix/hystrix/perf/CommandExecutionPerfTest.java

Added a first pass at jmh tests for hystrix-core

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixObservableCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/CommonHystrixCommandTests.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java

Only fire onFallbackStart/onFallbackError execution hooks if there is a user-supplied fallback

---

hystrix-contrib/hystrix-rx-netty-metrics-stream/build.gradle
hystrix-contrib/hystrix-rx-netty-metrics-stream/src/main/java/com/netflix/hystrix/contrib/rxnetty/metricsstream/HystrixMetricsStreamHandler.java

I updated the RxNetty based Hystrix Metrics Stream to a newer version of RxNetty that it could work with Karyon2.

Updated the RxNetty based version of HystrixMetricsStreamHandler

---

hystrix-contrib/hystrix-metrics-event-stream/build.gradle
hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsPoller.java
hystrix-contrib/hystrix-metrics-event-stream/src/test/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsPollerTest.java

Upgraded Jackson from 1.x to 2.5.2 and split out HystrixMetricsPoller unit test

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java

Handle hook errors

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCounters.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java

This helps address #297.  It is a counter around per-JVM concurrent threads. Rather than forcing consumers to implement this via hooks, you now can get it directly.

Added HystrixCounters to hold global metrics on Hystrix behavior

---

hystrix-dashboard/src/main/webapp/components/hystrixCommand/hystrixCommand.css
hystrix-dashboard/src/main/webapp/components/hystrixCommand/templates/hystrixCircuit.html
hystrix-dashboard/src/main/webapp/monitor/monitor.css
hystrix-dashboard/src/main/webapp/monitor/monitor.html

Added Bad Request count to Hystrix dashboard

---

hystrix-core/build.gradle
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCollapserMetrics.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandMetrics.java
hystrix-core/src/main/java/com/netflix/hystrix/util/HystrixRollingPercentile.java
hystrix-core/src/test/java/com/netflix/hystrix/util/HystrixRollingPercentileTest.java

Use HdrHistogram for latency percentile calculation

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/util/HystrixRollingPercentile.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/TestHystrixCommand.java

Instead of try-catching all hook errors, follow this pattern:
* For a hook at the beginning of an event, assume that a thrown exception replaces the surrounded event.  For example, `onExecutionStart()` throwing implies that the `run()`/`construct()` method does not get run, but it looks from the outside as if it threw an exception.
* For a hook at the end of an event, there is no such ability to replace a value, so just try-catch and log.
This allows for hooks to influence behavior without having to subclass `HystrixCommand`.  I've also added a unit test that asserts state is properly maintained when hooks throw Exceptions

More precise solution to #771

---

hystrix-contrib/hystrix-codahale-metrics-publisher/build.gradle

Latest version changed groupId to `io.dropwizard.metrics` from `com.codahale.metrics`

Update metrics to the latest version

---

hystrix-contrib/hystrix-metrics-event-stream/build.gradle
hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsStreamServlet.java
hystrix-contrib/hystrix-metrics-event-stream/src/test/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsStreamServletUnitTest.java

Reject requests with a 503 status code when the servlet has been shutdown. This prevents a new HystrixMetricsPoller to be started, defeating the original reason shutdown has been added (cf. #346).

HystrixMetricsStreamServlet rejects requests after servlet shutdown (fixes #786)

---

hystrix-dashboard/src/main/webapp/index.html

As suggested by @nurkiewicz during his GeeCON 2015 talk, pressing the enter key in the input field now directly starts the monitor.

Monitoring stream when pressing the enter key

---

hystrix-core/build.gradle
hystrix-core/src/jmh/java/com/netflix/hystrix/perf/MultiThreadedMetricsTest.java
hystrix-core/src/main/java/com/netflix/hystrix/util/HystrixRollingPercentile.java
hystrix-core/src/test/java/com/netflix/hystrix/util/HystrixRollingPercentileTest.java

Either cache the commonly-accessed summaries at construction, or support arbitrary calculations via a synchronized path
Addresses #788

Move all reads of Histograms to a single-threaded path

---

hystrix-core/src/main/java/com/netflix/hystrix/util/HystrixRollingNumber.java
hystrix-core/src/test/java/com/netflix/hystrix/util/HystrixRollingNumberTest.java

This change is still awaiting thorough performance testing.  The intent is to remove references for sun.misc.Unsafe and to generally prefer a simpler data structure (if it doesn't cost us performance).

Switching HystrixRollingNumber impl from LongAdder/LongMaxUpdater to AtomicLong

---

hystrix-core/src/main/java/com/netflix/hystrix/util/HystrixRollingPercentile.java
hystrix-core/src/test/java/com/netflix/hystrix/util/HystrixRollingPercentileTest.java

In practice, modifying the HystrixRollingPercentile data structure at runtime doesn't have the desired effect.  Modifying the data structure to actually allow for this is not straightforward and would cause data loss in some cases (when the window gets shortened).  Rather than allow for dynamic reconfiguration, this PR removes all instances where dynamic properties are queried at runtime.  It increases throughput on reads (while command executions are ongoing) by 40-60%.  In particular, caching the value of bucketSizeInMilliseconds avoids calling the division operation multiple times per read and write.

Remove all dynamic property lookups from HystrixRollingPercentile

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java

On recoverable java.lang.Error, log something so that application owners are notified, even as Hystrix serves a fallback

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPool.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPoolProperties.java

Modify logic to only check the dynamic maxQueueSize property on creation of a threadPool

---

hystrix-dashboard/src/main/webapp/components/hystrixCommand/hystrixCommand.css
hystrix-dashboard/src/main/webapp/components/hystrixCommand/templates/hystrixCircuitContainer.html
hystrix-dashboard/src/main/webapp/components/hystrixThreadPool/templates/hystrixThreadPoolContainer.html
hystrix-dashboard/src/main/webapp/monitor/monitor.html

Browsers hide the half of the mean metric in every command-monitor. I have fixed that. Later on we should maybe think about a solution based on percentages.

fix half hidden mean metric because of container height

---

hystrix-core/src/jmh/java/com/netflix/hystrix/perf/RollingPercentilePerfTest.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCollapserMetrics.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandMetrics.java
hystrix-core/src/main/java/com/netflix/hystrix/util/HystrixRollingPercentile.java
hystrix-core/src/test/java/com/netflix/hystrix/util/HystrixRollingPercentileTest.java

, not runtime.
This deprecates a constructor that accepted HystrixProperty<Integer> for these properties in favor of a new one, which accepts ints.
Also, the bucketSizeInMilliseconds() method was getting called frequently enough to cause the division to show up in CPU hot paths in production apps - precomputation should alleviate that problem

Make values for HystrixRollingPercentile bucket calculation only affect construction

---

hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsStreamServlet.java

Safely handle negative input on the delay input to metrics-stream

---

hystrix-dashboard/src/main/webapp/components/hystrixCommand/hystrixCommand.js

This fix adds validation for rollingCountBadRequests (added to the dashboard circuit template in v1.4.7), and also sets it to a default of 0 to provide backwards compatibility with older streams.

Add validation for rollingCountBadRequests

---

hystrix-core/src/test/java/com/netflix/hystrix/HystrixTest.java

To check behavior reported in #834

Reinstated HystrixTest and added unit test for modifying semaphore count

---

hystrix-contrib/hystrix-clj/src/main/clojure/com/netflix/hystrix/core.clj

From @daveray:
This is a fix for issue #831 (https://github.com/Netflix/Hystrix/issues/831) which
is a blocker for http://dev.clojure.org/jira/browse/CLJ-1232. Instead of generating
:arglists as (list (quote [..])*), generate (quote ([..]*)). Tests still
pass and (doc command) works as intended. I have not directly tested
this with Clojure patched with CLJ-1232.

Merge fix 851

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixRequestLogTest.java

Demonstrates problem from #847

Unit test demonstrating racy HystrixRequestLog

---

hystrix-core/build.gradle
hystrix-core/src/jmh/java/com/netflix/hystrix/perf/CommandGroupKeyExecutionPerfTest.java
hystrix-core/src/jmh/java/com/netflix/hystrix/perf/CommandSetterExecutionPerfTest.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommand.java

Addresses needless allocation from #850

Constructor allocation

---

hystrix-contrib/hystrix-rx-netty-metrics-stream/src/test/java/com/netflix/hystrix/HystrixCommandMetricsSamples.java
hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCollapserMetrics.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandMetrics.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandMetricsSummary.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixMetrics.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPoolMetrics.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/HystrixPlugins.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/metrics/HystrixCollapserMetricsSummary.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/metrics/HystrixCommandMetricsSummary.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/metrics/HystrixMetricsCollection.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/metrics/HystrixMetricsCollectionDefault.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/metrics/HystrixThreadPoolMetricsSummary.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/metrics/noop/HystrixCollapserMetricsNoOp.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/metrics/noop/HystrixCommandMetricsCountsOnly.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/metrics/noop/HystrixMetricsCollectionMinimal.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/metrics/noop/HystrixThreadPoolMetricsNoOp.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCircuitBreakerTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandMetricsTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixThreadPoolMetricsTest.java

This addresses the concern of #333.  This PR is intended to be a PoC to demonstrate that there can be varying implementations of metric collection (command/thread pool/collapser).  The version which summarizes via HystrixRollingNumber/HystrixRollingPercentile is one such concrete implementation.
This PR is not ready for merging - I still would like to:
* Clean up the Javadoc
* Add Wiki documentation around the new plugin
* Add no-op metrics strategies to evaluate perf impact
* Make sure I didn't impact any public methods
* Convince myself that new abstract methods are the proper set for concrete impls
If anyone has feedback along those lines, it would be appreciated.

Make hystrix metrics abstract

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java

* This helps performance and eliminates chance that start/end of command see this value differently

Only lookup if the request cache is enabled once per command invocation

---

hystrix-core/src/jmh/java/com/netflix/hystrix/perf/ObservableCollapserPerfTest.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCollapser.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixObservableCollapser.java
hystrix-core/src/main/java/com/netflix/hystrix/collapser/CollapsedRequestObservableFunction.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCollapserTest.java

Replaces #881.  Fixed memory consumption issue by replacing `ReplaySubject` with `PublishSubject` and adding an `AtomicBoolean` to `CollapsedRequestObservableFunction` to track if a value has been set on the response yet

Multiple responses per collapser arg

---

hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/cache/HystrixCacheKeyGenerator.java

When no @CacheKey are specified, a null pointer occurred. This fixes it.

Fix missing null check in HystrixCacheKeyGenerator.

---

hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/cache/HystrixCacheKeyGenerator.java

From @fredboutin:
When no @CacheKey are specified, a null pointer occurred. This fixes it.

Backport of #896

---

hystrix-contrib/hystrix-javanica/build.gradle
hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/cache/CacheInvocationContext.java
hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/conf/HystrixPropertiesManager.java

This library was only used in two places:
- HystrixPropertiesManager.java: A simple null check works in its place. (Though I think this null check would be safe to remove as well.)
- CacheInvocationContext.java: The field keyParameters will not be null so
calling isEmpty directly will not result in a NullPointerException.
This is one less dependency to manage and avoids bringing in a ~500k jar for
null checks.

Remove commons-collections dependency.

---

hystrix-contrib/hystrix-javanica/build.gradle
hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/cache/CacheInvocationContext.java
hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/conf/HystrixPropertiesManager.java

This library was only used in two places:
- HystrixPropertiesManager.java: A simple null check works in its place.
- CacheInvocationContext.java: The field keyParameters will not be null so
calling isEmpty directly will not result in a NullPointerException.
This is one less dependency to manage and avoids bringing in a ~500k jar for
null checks.

Remove commons-collections dependency. (Backport of #899)

---

hystrix-examples/src/main/java/com/netflix/hystrix/examples/basic/ObservableCollapserGetWordForNumber.java
hystrix-examples/src/main/java/com/netflix/hystrix/examples/basic/ObservableCommandNumbersToWords.java

This was based on a discussion in [895](https://github.com/Netflix/Hystrix/issues/895). I've modified the [original example](https://github.com/ruhkopf/ExampleAsyncHystrixObservableCollapserExample) to be compatible with JDK 6, removed the dependency to ICU and refactored the test class to be part of the command class to match the pattern used for other examples.

observable collapser example

---

hystrix-dashboard/src/main/webapp/monitor/monitor.html

Use JQuery .text() function to escape title to avoid any XSS attacks.

fix(title-xss): escaping text acquired from parameters to avoid any xss attacks

---

hystrix-dashboard/src/main/webapp/components/hystrixCommand/templates/hystrixCircuit.html

isCircuitBreakeropen is assumed to be a boolean from the HystrixStream servlet, however these replace() operations assume that it is a string. There are certain instances where Turbine does not return back a String when isCircuitBreakerOpen is aggregated. This enforces the boolean to be a string first, regardless of what Turbine may/may not do.

[hystrix-dashboard] isCircuitBreakerOpen is assumed to be a boolean

---

hystrix-contrib/hystrix-codahale-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisher.java
hystrix-contrib/hystrix-servo-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisher.java
hystrix-contrib/hystrix-yammer-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/yammermetricspublisher/HystrixYammerMetricsPublisher.java

The included implementations of HystrixMetricsPublisher didn't override the getMetricsPublisherForCollapser method - since there are already implementations of HystrixMetricsPublisherCollapser available for each one, I've added the method for all of them.

Support collapser metrics in HystrixMetricPublisher implementations

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/exception/HystrixTimeoutException.java

Make HystrixTimeoutException public so that user-defined execution methods may return it

---

hystrix-dashboard/src/main/webapp/monitor/monitor.html

Backport of #919 from @william-tran

Dashboard: 2 listeners to same EventSource

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixConcurrencyStrategy.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixLifecycleForwardingRequestVariable.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixRequestVariableHolder.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java

Design change as mentioned in #92

Push RequestContext tolerance into ConcurrencyStrategy

---

hystrix-contrib/hystrix-clj/src/main/clojure/com/netflix/hystrix/core.clj

this way if someone uses it they won't get reflection

tag *command* as a HystrixCommand

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixCollapserProperties.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandProperties.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPoolProperties.java

Added defaultSetter() methods to properties classes as a workaround for GROOVY-6286

---

hystrix-dashboard/src/main/webapp/components/hystrixCommand/hystrixCommand.css
hystrix-dashboard/src/main/webapp/components/hystrixCommand/hystrixCommand.js
hystrix-dashboard/src/main/webapp/components/hystrixCommand/templates/hystrixCircuitContainer.html
hystrix-dashboard/src/main/webapp/components/hystrixThreadPool/hystrixThreadPool.js
hystrix-dashboard/src/main/webapp/components/hystrixThreadPool/templates/hystrixThreadPoolContainer.html
hystrix-dashboard/src/main/webapp/css/global.css
hystrix-dashboard/src/main/webapp/index.css
hystrix-dashboard/src/main/webapp/index.html
hystrix-dashboard/src/main/webapp/monitor/monitor.html

Create a list of hystrix streams to monitor and monitor them independently
using a monitor page.
Backward compatible with existing monitor web url bookmarks.
Implements #906.

Enable Hystrix Dashboard to monitor multiple independent applications

---

hystrix-contrib/hystrix-javanica/build.gradle

Upgrade commons collections since there is a bit of hysteria around the security issue (and it won't be dragged in transitively by end-users).
Always good to stay current anyways.

upgrade to commons-collections 3.2.2

---

hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCollapserTest.java

Tests to exercise scenario in #955

Adding a test of concurrent HystrixObservableCollapsers running

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTimeoutConcurrencyTesting.java

As described in #985.
When I adjust the number of concurrent commands upwards, I sporadically see failures.  Those seem exactly as described by @jojitj.
Now that I have a fairly-reliable repro, I'll investigate why this is happening and get a fix out.

Made commands run concurrently in HystrixCommandTimeoutConcurrencyTesting

---

hystrix-dashboard/src/main/webapp/index.html

Clicking on Add Stream button should reset any error messages that were
displayed on the previous failed attempt.
See #991 for more details.

Remove validation error message when adding a stream to monitor

---

hystrix-core/src/test/java/com/netflix/hystrix/CommonHystrixCommandTests.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCircuitBreakerTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/InspectableBuilder.java
hystrix-core/src/test/java/com/netflix/hystrix/TestHystrixCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/TestHystrixObservableCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/TestableExecutionHook.java

This makes unit tests more concise and decouples command unit tests from metrics

Modify unit tests to assert on event counts and ordering instead of metrics gathered

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandMetrics.java

Raised by @JorritSalverda in #1031

Remove SHORT-CIRCUITs from Health check calculation

---

hystrix-core/src/main/java/com/netflix/hystrix/Hystrix.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixTest.java

Addresses #1012.  The `testMultipleSemaphoreObservableCommandsInFlight` unit test failed consistently when using a `LinkedList` instead of the `ConcurrentStack`.
Would you mind taking a look, @mzeijen?  Thanks again for bringing this up.  I'll add the deprecation as the next commit if you think this looks like the right approach.

Make methods of Hystrix class thread-safe

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixObservableCollapser.java
hystrix-core/src/main/java/com/netflix/hystrix/collapser/CollapsedRequestObservableFunction.java
hystrix-core/src/main/java/com/netflix/hystrix/collapser/RequestCollapser.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCollapserTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCollapserTest.java

Addresses #955 
1) Batch command failure was not handing this exception out to each collapser waiting for a value
2) Synchronous error thrown in submit request changed to Observable.error(...)
3) Cached HystrixCollapserProperties in unit test to ensure we didn't hit Archauis bottleneck
4) Added unit test for batch command failing and matched behavior to HystrixCollapser

A couple approaches to fix HystrixObservableCollapser not producing values

---

hystrix-core/src/jmh/java/com/netflix/hystrix/perf/CommandExecutionPerfTest.java

* Measures both `HystrixCommand` and `HystrixObservableCommand`
* Measures impact of `HystrixRequestContext`
* Adds blackhole to baseline measurements to see how CPU utilization degrades in Hystrix and non-Hystrix cases

Better measurement of command execution

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixTimerThreadPoolProperties.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/properties/HystrixPropertiesStrategy.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/properties/HystrixPropertiesTimerThreadPoolDefault.java
hystrix-core/src/main/java/com/netflix/hystrix/util/HystrixTimer.java
hystrix-core/src/test/java/com/netflix/hystrix/util/HystrixTimerTest.java

I implemented a simple way to configure the timeout thread pool core size via a system property. The default is still Runtime.getRuntime(). availableProcessors(). I also added test cases for this feature.

Implementation for feature request #1013

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPool.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixTest.java

Changed the return type from ThreadPoolExecutor to ExecutorService, the intention is to support hystrix running on parallel universe quasar, since quasar uses ForJoinPool internally, this change has to be made. see ticket #903

changed HystrixThreadPool.getExecutor() return type

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/CommonHystrixCommandTests.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java

This makes it more apparent what's getting set up and what dependencies exist between values

Modularized command constructor logic to make it easier to read

---

hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsPoller.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixConcurrencyStrategy.java
hystrix-core/src/main/java/com/netflix/hystrix/util/HystrixTimer.java
hystrix-core/src/main/java/com/netflix/hystrix/util/PlatformSpecific.java

If so, provide the AppEngine-specified ThreadFactory.  This should resolve #795.

Added PlatformSpecific class that can detect if it's running in AppEngine

---

hystrix-contrib/hystrix-codahale-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisherCommand.java
hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsPoller.java
hystrix-contrib/hystrix-rx-netty-metrics-stream/src/main/java/com/netflix/hystrix/contrib/rxnetty/metricsstream/JsonMappers.java
hystrix-contrib/hystrix-servo-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisherCommand.java
hystrix-contrib/hystrix-yammer-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/yammermetricspublisher/HystrixYammerMetricsPublisherCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/ExecutionResult.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandMetrics.java

Deprecate methods to retrieve userThreadLatency, and remove it from standard metrics being published

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixRequestCache.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixRequestVariableHolder.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixRequestCacheTest.java

I'm new to Hystrix, so I'm not sure this is the ideal implementation.
This might fix https://github.com/Netflix/Hystrix/issues/995 .

Fixed NPE on request cache when HystrixRequestContext is not initialized

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixRequestCache.java

Fixes null check introduced in #1093.
The idea in #1093 was correct, but didn't use the concurrency strategy.  I fixed that, and also added the same null check to the write path

Delegate HystrixRequestCache check through concurrency strategy

---

hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/cache/HystrixRequestCacheManager.java

This can result in unexpected results if the concurrency strategy has overridden getRequestVariable. In my case this resulted in a NPE when clearing the cache entry

Javanica HystrixRequestCacheManager should use the concurrency strategy from HystrixPlugins

---

hystrix-dashboard/src/main/webapp/index.html
hystrix-dashboard/src/main/webapp/monitor/monitor.html

Fix underscore.js URL to work correctly both on http:// and https://

Fix underscore.js URL

---

hystrix-contrib/hystrix-codahale-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisherCommand.java
hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsPoller.java
hystrix-contrib/hystrix-rx-netty-metrics-stream/src/main/java/com/netflix/hystrix/contrib/rxnetty/metricsstream/JsonMappers.java
hystrix-contrib/hystrix-servo-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisherCommand.java
hystrix-contrib/hystrix-yammer-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/yammermetricspublisher/HystrixYammerMetricsPublisherCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/ExecutionResult.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandMetrics.java

This reverts commit cf3d12f8698cd28ea0350c110f3553975b2b832b. PR #1075 
Upon second thought (and contact with the real world), don't do this.  Shouldn't break backwards-compatibility of existing stream formats

Revert "Deprecate methods to retrieve userThreadLatency, and remove it from standard metrics being published"

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java

Making the HystrixTimeoutException instance per-command, not static

---

hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsPoller.java
hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsStreamServlet.java

Turning down loglevels of metrics streams

---

hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java

Multiple acquisition was the result of 1 command finishing before the last had been invoked.  Increasing the time spent in the command should eliminate this condition

Deflaked test of semaphore concurrency

---

hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsStreamServlet.java

The queue size of the MetricJsonListener used by the HystrixMetricsStreamServlet has been made configurable in two ways:
- new property "hystrix.stream.defaultMetricListenerQueueSize", which if unspecified will be set to 1000
- optional request parameter "queueSize", which can override the default queue size for each request
The changes have been made on the 1.4.x, but can also be propagated to the 1.5.x RC branch. Please let me know if you need any further information or would like to suggest changes.

#1109 Make queue size of MetricJsonListener configurable

---

hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsStreamServlet.java

Make queue size of MetricJsonListener configurable

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixCollapserProperties.java

HystrixCollapserProperties.getProperty(String, HystrixCollapserKey, String, String, String)
Brought up in #1150

Remove unused method 

---

hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/cache/HystrixCacheKeyGenerator.java
hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsPoller.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPoolMetrics.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPoolProperties.java
hystrix-core/src/main/java/com/netflix/hystrix/util/HystrixRollingNumber.java

I found more unused methods and variables related with  https://github.com/Netflix/Hystrix/issues/1150

Removed methods and variables with unused annotation

---

hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsPoller.java

Make HystrixMetricPoller a daemon thread to allow application shutdown gracefully

HystrixMetricsPoller as a daemon thread

---

hystrix-contrib/hystrix-javanica/README.md
hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/AbstractHystrixCommand.java
hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/BatchHystrixCommand.java
hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/GenericCommand.java
hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/GenericObservableCommand.java

fixes gh-1155
Backport of #1167

Use getExecutionException to handle timeout, short-circuit, etc... exceptions

---

hystrix-contrib/hystrix-junit/build.gradle
hystrix-contrib/hystrix-junit/src/main/java/com/hystrix/junit/HystrixRequestContextRule.java
hystrix-contrib/hystrix-junit/src/test/java/com/hystrix/junit/HystrixRequestContextRuleTest.java
settings.gradle

This will make testing commands that requires a `HystrixRequestContext`
easier in JUnit by using its Rule feature.
An example of usage would be something like:
```java
@Rule
public HystrixRequestContextRule request = new HystrixRequestContextRule();
@Test
public void blah() {
// exec a HystrixCommand that requires some kind of caching, for example
}
```
I put it in the `hystrix-contrib` folder, let me know if this is the right thing to do, please.

Proposal: HystrixRequestContext junit rule

---

hystrix-contrib/hystrix-junit/build.gradle
hystrix-contrib/hystrix-junit/src/main/java/com/hystrix/junit/HystrixRequestContextRule.java
hystrix-contrib/hystrix-junit/src/test/java/com/hystrix/junit/HystrixRequestContextRuleTest.java
settings.gradle

HystrixRequestContext junit rule

---

hystrix-contrib/hystrix-javanica/build.gradle
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/BasicHystrixTest.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/cache/BasicCacheTest.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/collapser/BasicCollapserTest.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/command/BasicCommandTest.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/configuration/collapser/BasicCollapserPropertiesTest.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/configuration/command/BasicCommandPropertiesTest.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/error/BasicErrorPropagationTest.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/fallback/BasicCommandFallbackTest.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/observable/BasicObservableTest.java
hystrix-contrib/hystrix-junit/src/main/java/com/hystrix/junit/HystrixRequestContextRule.java

using the rule created on #1147 on all hystrix-javanica tests.
Also improved the rule a bit.
cc/ @mattrjacobs

migrating all hystrix-javanica tests to hystrix-junit

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixCollapserProperties.java

I might be mistaken, but it looks like the "collapsingEnabled" property in HystrixCollapserProperties.Setter doesn't ever get used, which is kind of confusing, since I had assumed it would actually enable/disable collapsing. So I figure a straightforward way to avoid people using it in the future is Deprecation in current versions and removing it 2.x or whatever. Thoughts? I can submit another pull request to remove it from the 2.x branch if that's a good idea.

Deprecate getter and setter for unused collapsingEnabled property in Collapser Setter.

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixCollapserProperties.java

These were deprecated in 1.5.3/1.4.27 and PR #1181.  Work done there by @nluchs

Removing unused methods for collapsingEnabled on HystrixCollapserProperties

---

hystrix-core/build.gradle
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCollapserTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCollapserTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixRequestLogTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixSubclassCommandTest.java

Replaced the manual `HystrixRequestContext` inits and shutdowns with the junit rule.
My IDE also auto-fixed some trailing whitespaces, that's why the pull seems a little big. A `diff -w` should do the trick.
refs https://github.com/Netflix/Hystrix/pull/1184 and https://github.com/Netflix/Hystrix/pull/1147
cc/ @mattrjacobs

more tests using HystrixRequestContext rule

---

hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java

all tests were doing stuff like `try { something(); } catch (Exception e) { fail(); }`, I removed those try-catch blocks were I thought was safe to.
I also removed some commented out code..

improved tests readbility a bit

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/CommonHystrixCommandTests.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java

3 fixes in this PR:
* execution semaphore was not being released
* fallback semaphore was not being released
* isExecutionComplete was not set to true

Add test cases for unsubscribe of Hystrix commands before terminal events

---

hystrix-contrib/hystrix-codahale-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisherCollapser.java
hystrix-contrib/hystrix-codahale-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisherCommand.java
hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsPoller.java
hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/sample/stream/HystrixSampleSseServlet.java
hystrix-contrib/hystrix-request-servlet/src/main/java/com/netflix/hystrix/contrib/requestservlet/HystrixRequestLogViaLoggerServletFilter.java
hystrix-contrib/hystrix-rx-netty-metrics-stream/src/main/java/com/netflix/hystrix/contrib/rxnetty/metricsstream/JsonMappers.java
hystrix-contrib/hystrix-servo-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisherCollapser.java
hystrix-contrib/hystrix-servo-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisherCommand.java
hystrix-contrib/hystrix-servo-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisherThreadPool.java
hystrix-contrib/hystrix-yammer-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/yammermetricspublisher/HystrixYammerMetricsPublisherCollapser.java
hystrix-contrib/hystrix-yammer-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/yammermetricspublisher/HystrixYammerMetricsPublisherCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixObservableCollapser.java
hystrix-core/src/main/java/com/netflix/hystrix/collapser/RequestCollapserFactory.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/properties/HystrixPropertiesChainedArchaiusProperty.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/properties/HystrixPropertiesChainedProperty.java
hystrix-dashboard/src/main/java/com/netflix/hystrix/dashboard/stream/ProxyStreamServlet.java

avoid String building if the log level doesn't cause the line to be logged.

use parameterized logging

---

hystrix-contrib/hystrix-servo-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisherCommand.java
hystrix-contrib/hystrix-servo-metrics-publisher/src/test/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisherCommandTest.java

Fix Servo percentile calculation

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCounters.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java

* Also made onThreadComplete hook fire as soon as user-provided execution emits terminal or is unsubscribed

Fixing unsubscription races by modeling explicit FSMs for command and thread execution state

---

hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/aop/aspectj/HystrixCommandAspect.java
hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/utils/FallbackMethod.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/properties/HystrixPropertiesChainedArchaiusProperty.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/properties/HystrixPropertiesChainedProperty.java

Hi. This is a small thing, but I noticed this grammatical error in the logs and thought I could fix it in a jiffy.

improve usages of "its" and "it's"

---

hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/utils/EnvUtils.java

Enum.valueOf throws an exception, and does not return null, so handle invalid value that way.

fix handling of invalid weavingMode property

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPool.java

This contribution will make Hystrix run faster in JDK 6.  Since when create a `HystrixCommand`, `HystrixThreadPoolDefault.touchConfig` will be executed, then execute`ThreadPoolExecutor.setCorePoolSize` and `ThreadPoolExecutor.setMaximumPoolSize`.  These two methods will execute `mainLock.lock()` all the time.  That is negative to the performance.
The improve is to check whether pool size will be changed or not before set this value.
This contribution will not affect JDK 7 and 8.

Set the thread pool size only when the configuration is changed.

---

hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/utils/MethodProvider.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/spring/fallback/InheritedFallbackTest.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/util/GetMethodTest.java

link https://github.com/Netflix/Hystrix/issues/1177

iss1177: change getMethod to recursively search in parent types

---

hystrix-contrib/hystrix-clj/src/test/clojure/com/netflix/hystrix/core_test.clj
hystrix-contrib/hystrix-rx-netty-metrics-stream/src/main/java/com/netflix/hystrix/contrib/rxnetty/metricsstream/HystrixMetricsStreamHandler.java
hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java

Prevents work (like cache key calculation) from happening before subscription
* This also implies that queue()/observe() will not throw anymore
* The IllegalStateException now gets wrapped in a HystrixRuntimeException

Make toObservable lazy.  

---

hystrix-core/build.gradle
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandGroupKey.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandKey.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixKey.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPoolKey.java
hystrix-core/src/main/java/com/netflix/hystrix/util/InternMap.java

Fix rare case when this method would return different values for the same key
The problem would happen when:
1. Thread1: No such key when intern.get(name), so k was null
2. Thread1: We would enter if-statement
3. Thread2: Other thread would add key to intern map
4. Thread1: We will not put new key to intern map, but we will return newly created value instead of one stored in map

Fix race condition in HystrixThreadPoolKey.asKey method

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixCollapser.java

Made HystrixCollapser.toObservable lazy by wrapping all work in an Observable.defer

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixCollapser.java
hystrix-core/src/main/java/com/netflix/hystrix/collapser/CollapsedRequestSubject.java
hystrix-core/src/main/java/com/netflix/hystrix/collapser/RequestBatch.java
hystrix-core/src/main/java/com/netflix/hystrix/collapser/RequestCollapser.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/properties/HystrixPropertiesFactory.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCollapserTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCollapserTest.java

If this is attempted, then 1 of 2 things can occur:
If request-caching is on: the response for the 2nd-nth instance of the argument is the same as the first
If off: the response for the 2nd-nth instance of the argument is an error
This fixes the failing unit test supplied in #1176

Prevent duplicate arguments from getting into a single collapser RequestBatch

---

hystrix-examples/src/main/java/com/netflix/hystrix/examples/basic/ObservableCollapserGetWordForNumber.java

This test case fails because two `ObservableCollapserGetWordForNumber` commands are collapsed, both of them having the same request argument. Test passes with:
TestSubscriber<String> subscriber1 = getWordForNumber(contextAwareScheduler, 0);
TestSubscriber<String> subscriber2 = getWordForNumber(contextAwareScheduler, 1);
//then
subscriberReceived(subscriber1, 0);
subscriberReceived(subscriber2, 1);
The error is:
java.lang.IllegalStateException:
No response set by ObservableCollapserGetWordForNumber 'mapResponseToRequests' implementation
Looks like [here](https://github.com/Netflix/Hystrix/blob/master/hystrix-core/src/main/java/com/netflix/hystrix/HystrixObservableCollapser.java#L176) requests with the same argument are silently ignored. When response later arrives they are not populated. …

Failing test case when two requests with the same request argument are collapsed

---

hystrix-contrib/hystrix-javanica/src/ajcTest/java/com/netflix/hystrix/contrib/javanica/test/aspectj/error/ObservableErrorPropagationTest.java
hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/aop/aspectj/HystrixCommandAspect.java
hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/GenericObservableCommand.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/error/BasicObservableErrorPropagationTest.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/spring/error/ObservableErrorPropagationTest.java

Corrected not working ignoreExceptions for Observables. Issue #1272
- changed GenericObservableCommand to correctly wrap ignorable exceptions in HystrixBadRequestException using Observable.onErrorResumeNext,
- changed HystrixCommandAspect to uwrap HystrixBadRequestException and HystrixRuntimeException conveyed by observble the same way as normally thrown exceptions are uwrapped,
- added test for ignoring errors in observables similar to BasicErrorPropagationTest.

Corrected ignoreExceptions for Observable returning methods.

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPool.java

When HystrixThreadPool.shutdown is called with a timeout, a single call to awaitTermination is called.
This is now done in a loop to make sure the thread-pool is definitely shutdown.

Make sure thread-pools actually shutdown

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandProperties.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandPropertiesTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java

The implementation of java.util.concurrent.Future returned by com.netflix.hystrix.HystrixCommand#queue()#cancel(boolean mayInterruptIfRunning) ignores the "mayInterruptIfRunning" flag and never calls Thread#interrupt() on Hystrix Execution Thread running the command's run() method. This complicates the handling of situations where commands have to be interrupted. I am not sure it would make sense to enable the interruption of the getFallback() method, as well-behaved fallbacks probably should not do stuff that may require interruption.
The interruption of the execution thread IMO makes sense only through the invocation of the Future#cancel(boolean) method. The command should not be interruptible if executed via com.netflix.hystrix.HystrixCommand#execute() (blocking invocation forfeits …

Interrupt execution thread on HystrixCommand#queue()#cancel(true)

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixObservableCommand.java

* Should allow Javanica to re-implement this concept straightforwardly

Made the user-defined fallback calculation more general

---

hystrix-dashboard/src/main/webapp/index.css
hystrix-dashboard/src/main/webapp/index.html

Hello!
Did some improvements on Hystrix Dashboard Eureka Integration, hope it helps!
The following was improved:
- Added remove button for added streams
- Refactored the javascript code on index
- Updating url on changing stream type
- Updated the url scheme to consider the port on eureka, instead of using only 8080, useful when using ephemeral ports, for example on local dev deployment.
- Update title for application name, after you select the application, the title will be updated with it's name
- Updated the list of apps list all the applications instances
- Updated the list to group the instances by application name
- Added a group called "applications" that will have the first instance of each application, maintaining a similiar behaviour to the the legacy implementation, although …

Hystrix Dashboard Eureka integration improvements

---

hystrix-core/src/main/java/com/netflix/hystrix/metric/CachedValuesHistogram.java

Remove object-pooling from CachedValuesHistogram

---

hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsPoller.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixConcurrencyStrategy.java
hystrix-core/src/main/java/com/netflix/hystrix/util/HystrixTimer.java
hystrix-core/src/main/java/com/netflix/hystrix/util/PlatformSpecific.java

Fixes #1352.
App Engine now has two environments, Standard and Flexible. The Flexible environment is just a Docker container, and as such can use standard Java threading. This change detects the Flexible environment via an environment variable that does not exist in the Standard environment, but exists for Flexible (both in local development and in production).

Update PlatformSpecific to only detect App Engine Standard Environment

---

hystrix-core/src/jmh/java/com/netflix/hystrix/perf/CommandConstructionPerfTest.java

Otherwise, data structures are cached and constructions does less work

jmh test is more accurate when measuring the first command construction

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPoolMetrics.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixThreadPoolMetricsTest.java

Filter out all thread pool objects from thread pool metric streams which have not executed a command

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPoolMetrics.java
hystrix-core/src/main/java/com/netflix/hystrix/util/PlatformSpecific.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixThreadPoolMetricsTest.java

Accidentally introduced incompatibility in #1356 .
This PR restores `PlatformSpecific.isAppEngine()` and changes the boolean tracking which platform is found (GAE-Standard / anything else) to a 3-valued enum (STANDARD / APPENGINE_STANDARD / APPENGINE_FLEXIBLE)

Fix backwards incompatibility for appengine

---

hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/sample/stream/HystrixConfigurationJsonStream.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPool.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPoolProperties.java
hystrix-core/src/main/java/com/netflix/hystrix/config/HystrixThreadPoolConfiguration.java
hystrix-core/src/test/java/com/netflix/hystrix/AbstractTestHystrixCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixThreadPoolPropertiesTest.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixThreadPoolTest.java
hystrix-core/src/test/java/com/netflix/hystrix/InspectableBuilder.java
hystrix-serialization/src/main/java/com/netflix/hystrix/serial/SerialHystrixConfiguration.java

With this change, it is possible to set `coreSize < maximumSize` and have a thread pool which can give up threads if they become inactive (subject to the keep-alive time).
Design considerations:
* An `IllegalArgumentException` is thrown if a `ThreadPoolExecutor` is configured with `coreSize > maximumSize`.  When that condition occurs when the constructor is invoked, this PR chooses to use `coreSize` for `maximumSize` to avoid the error and logs something to the user.
* This PR uses the discovered `coreSize` as the default value for `maximumSize`.  This should allow a clean migration, as no one currently has `maximumValue` configured.  So without that config, Hystrix should configure itself as before - a fixed size threadpool of size `coreSize`.  Further configuration can then set these …

Add threadPool maximumSize configuration

---

hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixContextScheduler.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java

This addresses #372.
Note that the solution is much simpler than discussed in #372.  Since we control the object handed back to the caller (`Future` / `Observable`), we can straightforwardly add the queue removal operation to the unsubscription.
As in the `ScheduledThreadPoolExecutor.removeOnCancelPolicy` solution that JDK7 uses, this only applies to work sitting in the queue.  Work already in the pool is handled directly by the JDK.

Remove cancelled work from the threadpool queue

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPool.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPoolProperties.java

@mattrjacobs , what do you think?

Remove outdated comments regarding thread keep alive.

---

hystrix-core/src/jmh/java/com/netflix/hystrix/perf/CommandExecutionPerfTest.java

This should help understand #1370

Add jmh test when circuit opened

---

hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/annotation/DefaultProperties.java
hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/annotation/HystrixCommand.java
hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/annotation/HystrixException.java
hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/aop/aspectj/HystrixCommandAspect.java
hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/MetaHolder.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/error/BasicDefaultIgnoreExceptionsTest.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/error/BasicDefaultRaiseHystrixExceptionsTest.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/spring/error/DefaultRaiseHystrixExceptionsTest.java

Adds the option to allow _HystrixRuntimeException_ to be thrown by `HystrixCommandAspect`.
The new property _raiseHystrixExceptions_ is supported by both `DefaultProperties` and `HystrixCommand`.
e.g.
```java
@DefaultProperties(
ignoreExceptions = BadRequestException.class,
raiseHystrixExceptions = {HystrixException.RUNTIME_EXCEPTION})
```
This pattern is extensible should people wish to add support for other Hystrix exceptions.
PR [requested](https://github.com/Netflix/Hystrix/issues/1344#issuecomment-254999908) by @dmgcodevil

Add option to raise HystrixRuntimeException

---

hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java

Added unit test that demonstrates calling .retry() on an Observable produced by Hystrix does not result in deadlock

---

hystrix-contrib/hystrix-clj/src/main/clojure/com/netflix/hystrix/core.clj

Fixes a typo in the `:hystrix/shard-fn` keyword option to the collapser creation macro.

Fix typo in collapser options keyword name (from shared-fn to shard-fn)

---

hystrix-contrib/hystrix-javanica/README.md
hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/aop/aspectj/HystrixCommandAspect.java
hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/error/BasicDefaultRaiseHystrixExceptionsTest.java

Adds support for Observable HystrixCommands to optionally raise `HystrixRuntimeException`. 
This extends upon https://github.com/Netflix/Hystrix/pull/1397
e.g.
```java
@HystrixCommand(raiseHystrixExceptions = {HystrixException.RUNTIME_EXCEPTION})
public Observable<User> getUserById(final String id) {
// ...
}
```

Javanica/Support raiseHystrixExceptions for Observables

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPool.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPoolProperties.java
hystrix-core/src/main/java/com/netflix/hystrix/config/HystrixThreadPoolConfiguration.java

Properly handle default values for `allowMaximumSizeToDivergeFromCoreSize` when configuring properties using Archaius.
Fixes #1434

Properly handle default values for allowMaximumSizeToDivergeFromCoreSize

---

hystrix-contrib/hystrix-codahale-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisherThreadPool.java
hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/sample/stream/HystrixConfigurationJsonStream.java
hystrix-contrib/hystrix-servo-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisherThreadPool.java
hystrix-contrib/hystrix-yammer-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/yammermetricspublisher/HystrixYammerMetricsPublisherThreadPool.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPool.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPoolProperties.java
hystrix-core/src/main/java/com/netflix/hystrix/config/HystrixThreadPoolConfiguration.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixThreadPoolPropertiesTest.java
hystrix-serialization/src/main/java/com/netflix/hystrix/serial/SerialHystrixConfiguration.java

Builds on #1439 to distinguish the value configured as the maximum for the threadpool, and the value actually applied.  In cases where the maximum was being pushed out, now both are.

Single method which ensures core less than equal to maximum

---

hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/error/BasicErrorPropagationTest.java

Added a test to the javanica project to verify #1414; that a check exception is thrown, without being wrapped in runtime exception.

Add Javanica test for NotWrapped checked exception

---

hystrix-contrib/hystrix-codahale-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisherCommand.java

Make exporting of newly added property to dropwizard. Original issue is https://github.com/Netflix/Hystrix/issues/54 and pull request adding given metrics is mentioned here https://github.com/Netflix/Hystrix/pull/667 .

Added exporting of rollingMaxConcurrentExecutionCount value.

---

hystrix-contrib/hystrix-metrics-event-stream-jaxrs/README.md
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/build.gradle
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/main/java/com/netflix/hystrix/contrib/metrics/HystrixStream.java
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/main/java/com/netflix/hystrix/contrib/metrics/HystrixStreamFeature.java
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/main/java/com/netflix/hystrix/contrib/metrics/HystrixStreamingOutputProvider.java
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/main/java/com/netflix/hystrix/contrib/metrics/controller/AbstractHystrixStreamController.java
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/main/java/com/netflix/hystrix/contrib/metrics/controller/HystrixConfigSseController.java
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/main/java/com/netflix/hystrix/contrib/metrics/controller/HystrixMetricsStreamController.java
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/main/java/com/netflix/hystrix/contrib/metrics/controller/HystrixRequestEventsSseController.java
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/main/java/com/netflix/hystrix/contrib/metrics/controller/HystrixUtilizationSseController.java
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/test/java/com/netflix/hystrix/contrib/metrics/controller/HystricsMetricsControllerTest.java
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/test/java/com/netflix/hystrix/contrib/metrics/controller/HystrixConfigControllerTest.java
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/test/java/com/netflix/hystrix/contrib/metrics/controller/HystrixUtilizationControllerTest.java
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/test/java/com/netflix/hystrix/contrib/metrics/controller/StreamingOutputProviderTest.java
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/test/resources/test.properties
settings.gradle

This pull request adds a new module hystrix-metrics-event-stream-jaxrs which is based on JAX-RS rather than Servlet API. This module is helpful for applications which depend only on JAX-RS. See this [issue](https://github.com/Netflix/Hystrix/issues/1490)

hystrix-metrics-event-stream implementation using JAX-RS

---

hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixConcurrencyStrategy.java

`threadnumber` no need to be protected
and 
local variable `threadFactory` is never used

delete unuseful code in HystrixConcurrencyStrategy

---

hystrix-contrib/hystrix-codahale-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisherCommand.java
hystrix-contrib/hystrix-codahale-metrics-publisher/src/test/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisherCommandTest.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixEventType.java

Making `COMMAND_MAX_ACTIVE` convertible between `HystrixRollingNumberEvent` --> `HystrixEventType`
Fixing #1508 which was caused by #1489

Fixing https://github.com/Netflix/Hystrix/issues/1508

---

hystrix-dashboard/src/main/webapp/components/hystrixCommand/hystrixCommand.js

The motivation here is the "propertyValue_circuitBreakerForceOpen" is currently being checked to make sure there is a value.  
It would make sense that the "propertyValue_circuitBreakerForceClosed" value also be checked

assert the circuitBreakerForceClosed property

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java

@mattrjacobs , I am not sure, does this fix a bug introduced some time ago?
Also, again, I am not sure... if `eventNotifier.markCommandExecution` should actually be invoked after...
`circuitBreaker.markSuccess();`
like https://github.com/Netflix/Hystrix/releases/tag/v1.5.2

Move markCommandExecution after markEvent SUCCESS.

---

hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/main/java/com/netflix/hystrix/contrib/metrics/controller/AbstractHystrixStreamController.java
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/main/java/com/netflix/hystrix/contrib/metrics/controller/HystrixConfigSseController.java
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/main/java/com/netflix/hystrix/contrib/metrics/controller/HystrixMetricsStreamController.java
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/main/java/com/netflix/hystrix/contrib/metrics/controller/HystrixRequestEventsSseController.java
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/main/java/com/netflix/hystrix/contrib/metrics/controller/HystrixUtilizationSseController.java
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/test/java/com/netflix/hystrix/contrib/metrics/controller/StreamingOutputProviderTest.java

I had defined `currentConcurrentConnections` as a static variable in abstract class by mistake which caused it to be shared between implementations which was wrong. Now, I have moved it to the implementation class. This was the reason tests where failing sometimes.

Fixed a potential bug in metrics-event-stream-jaxrs

---

hystrix-dashboard/src/main/webapp/components/hystrixCommand/templates/hystrixCircuit.html

Hystrix Dashboard displays `[object Object]` on circuit status when isCircuitBreakerOpen is aggregate using Turbine stream.
I fixed it like this :

Support multiple circuit status for Hystrix Dashboard

---

hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/sample/stream/HystrixSampleSseServlet.java

See https://groups.google.com/forum/#!topic/hystrixoss/4o6VqIW0b7Y
I don't believe implementations of servlet writers should be throwing, but if they do, this code is now more resilient.

Add exception-handling to interactions with servlet writers

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCircuitBreaker.java
hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandMetrics.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCircuitBreakerTest.java

as health counts stream produces new values
* This allows for methods which imply reading the circuit-breaker status (isOpen/allowRequest) to be idempotent
* Added new method (attemptExecution), which command internally uses to actually manipulate status
Addresses #1541

Made circuit-opening happen in background

---

hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/error/BasicErrorPropagationTest.java
hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/NotWrappedByHystrixTestRuntimeException.java

Closes #1536
First of all I want to note that this change is **breaking** one as far as I can see.
While most of my motivation is in #1536 and I will put an overview and some extra thoughts here:
`Hystrix` had that nice idea that `BadRequestException` was designed to bypass fallbacks. It was a really nice feature that allowed users of `Hystrix` to make a difference between execution errors and some conditional (so called "expected") errors e.g. validation.
#1414 #1503 introduced that nice concept of exception unwrapping which is really cool and I'm grateful to authors to have this feature. It has only one flaw - it has broken an idea of `BadRequestException`. Now any exception that implements `ExceptionNotWrappedByHystrix` leaves no choice to user if he wants to have fallbacks available - …

Handle not wrapped exceptions same way as all other

---

hystrix-contrib/hystrix-codahale-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisherCommand.java
hystrix-contrib/hystrix-codahale-metrics-publisher/src/test/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisherCommandTest.java

Fix #1581 
Issue was twofold:
1) The metric-consuming streams were not being started
2) Since reads are only available after a window passes, we need to wait in the unit test for the value to show up

Get CodaHale metrics working by starting up the stream consumers

---

hystrix-core/src/main/java/com/netflix/hystrix/HystrixRequestCache.java

While an `IllegalStateException` is already thrown when the `ConcurrentHashMap` cannot be retrieved for getting or putting to it, this will also throw an exception when it is not available when clearing.

throw IllegalStateException if request cache is not available when clearing

---

hystrix-contrib/hystrix-codahale-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisher.java
hystrix-contrib/hystrix-codahale-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisherCommand.java
hystrix-contrib/hystrix-codahale-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisherThreadPool.java
hystrix-contrib/hystrix-codahale-metrics-publisher/src/test/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisherCommandTest.java

Currently, command and thread pool metrics are stored in the same root ( commandGroup.commandName... and HystrixThreadPool.commadGroup....).
This PR allows to store metrics in the provided root node i.e. hystrix.commandGroup.commandName... , so they are not stored in the same root as other metrics.

Possibility to add custom root node for command and thread pool metrics

---

hystrix-dashboard/src/main/webapp/index.html

Using [underscore escape](http://underscorejs.org/#escape) function, the user entered input is escaped.

Escape user entered input to avoid HTML injection. This fixes #1456

---

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java
hystrix-core/src/test/java/com/netflix/hystrix/UnsubscribedTasksRequestCacheTest.java

Change the observable value returned when the command was unsubscribed from an error to an empty value. This fixes #1603.

Issue 1603

---

.travis.yml
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/test/java/com/netflix/hystrix/contrib/metrics/controller/HystricsMetricsControllerTest.java
hystrix-contrib/hystrix-metrics-event-stream-jaxrs/src/test/resources/test.properties
hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java
hystrix-core/src/test/java/com/netflix/hystrix/UnsubscribedTasksRequestCacheTest.java

Reset HystrixPlugins before and after test to avoid test failure when running after other tests
The test seems to run OK on its own, but if it's run in an “all tests” run, the test throws the following exception:
```
java.lang.IllegalStateException: Another strategy was already registered.
at com.netflix.hystrix.strategy.HystrixPlugins.registerCommandExecutionHook(HystrixPlugins.java:328)
```
Calling `HystrixPlugins.reset()` before and after the test fixes this.

Stabilize tests

---

hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java

This fix addresses the build failure that occurred in https://travis-ci.org/Netflix/Hystrix/builds/370693316
The test assumed that the command actually had time to start executing. However, there's some code being executed before the `executedInThread` property is set to `true` in `AbstractCommand`. The timeout can occur during that phase, so it's possible for the test to fail under high load.
The fix adds a check to see whether the command had a chance to run, and only then asserts that it was executed on a thread.
I verified the fix by stopping the executing thread via a breakpoint just before the call to `executionResult.setExecutedInThread()`. The test fails without the fix under these circumstances, but succeeds with the fix in place.
@timbozo I hope this is the one that will get the …

Stabilize yet another test

---

hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixContextScheduler.java
hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixContextSchedulerAction.java

I was looking at the Hystrix code and found a missing alphabet
HystrixContexSchedulerAction -> HystrixContextSchedulerAction
thank you

fix typo 'HystrixContextSchedulerAction' class name
