Netflix/Hystrix

hystrix-core/src/main/java/com/netflix/hystrix/Hystrix.java, hystrix-core/src/main/java/com/netflix/hystrix/strategy/HystrixPlugins.java
=> Add the capability to reset HystrixPlugins and make Hystrix.reset() invoke it

hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsPoller.java
=> Handle an error during construction of a MetricsPoller more gracefully

hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
Replaces #515.  This now works after #579.
=> Add unit test that demonstrates non-blocking timeout for HystrixCommand.queue()

hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java
=> Fix flakiness of testSemaphorePermitsInUse

hystrix-contrib/hystrix-yammer-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/yammermetricspublisher/HystrixYammerMetricsPublisherCollapser.java
=> Added RequestCollapser metrics to Yammer Metrics Publisher

hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandMetricsTest.java
Test to confirm behavior discussed in #674 is correct
=> Add test to confirm that bad requests do not affect circuit breaker's computed error percentage

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandMetricsTest.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java
=> Fix current concurrent execution count

hystrix-contrib/hystrix-codahale-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisherThreadPool.java, hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsPoller.java, hystrix-contrib/hystrix-rx-netty-metrics-stream/src/main/java/com/netflix/hystrix/contrib/rxnetty/metricsstream/JsonMappers.java, hystrix-contrib/hystrix-servo-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisherThreadPool.java, hystrix-contrib/hystrix-yammer-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/yammermetricspublisher/HystrixYammerMetricsPublisherThreadPool.java, hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPool.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPoolMetrics.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java
=> Add command rejection metrics to HystrixThreadPoolMetrics

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java, hystrix-core/src/main/java/com/netflix/hystrix/strategy/executionhook/HystrixCommandExecutionHook.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java, hystrix-core/src/test/java/com/netflix/hystrix/TestableExecutionHook.java
=> Add execution hook for cache hit

hystrix-core/src/test/java/com/netflix/hystrix/CommonHystrixCommandTests.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
Another test to investigate #685
=> Added a test with higher semaphore counts to detect raciness

hystrix-contrib/hystrix-servo-metrics-publisher/README.md
Time saver for those wishing to test out easy Graphite integration vs digging through Servo doc and example code
=> Example code for publishing to Graphite

hystrix-core/build.gradle, hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixExecutable.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixObservable.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixObservableCollapser.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixObservableCommand.java
=> Fix Javadoc generation and some Javadoc warnings

hystrix-dashboard/src/main/webapp/monitor/monitor.html
=> Add error message to HTML when connecting to metrics source fails

hystrix-dashboard/src/main/webapp/components/hystrixCommand/templates/hystrixCircuit.html
Fixes #574.  Code change by @ramkarna
=> Add semaphore-rejected metric to commands in Hystrix dashboard

hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
=> Comment out flaky fallback rejection test

hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandProperties.java
Updated Javadoc, as recommended by #740
=> Update timeout javadoc

hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandProperties.java
=> Better deprecation documentation for HystrixCommandProperties.Setter

hystrix-dashboard/src/main/webapp/components/hystrixCommand/templates/hystrixCircuit.html
=> Add timed-out metrics to dashboard for semaphore commands

hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPoolProperties.java
Noticed in https://github.com/Netflix/Hystrix/issues/740#issuecomment-91488841
=> Fixed Javadoc for HystrixThreadPoolProperties.Setter

hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsPoller.java, hystrix-contrib/hystrix-rx-netty-metrics-stream/src/test/java/com/netflix/hystrix/HystrixCommandMetricsSamples.java, hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandMetrics.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixCircuitBreakerTest.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandMetricsTest.java
=> Add threadpool to hystrix-metrics-event-stream for each command

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
Fixes issue reported in https://groups.google.com/d/msg/hystrixoss/okozy1pJKys/n6Jbh4JkBlYJ
=> Circuit forced open by properties queried properly

hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandGroupKey.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandKey.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixCounters.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPoolKey.java
=> Add HystrixCounters methods to return number of commands/threadpools/groups

hystrix-contrib/hystrix-metrics-event-stream/README.md
just version upgrade in the readme to prevent others from use an old version..
=> update readme to latest version

.travis.yml
Based on instructions here: http://docs.travis-ci.com/user/migrating-from-legacy/
=> Added Travis config so it can run in a container

hystrix-contrib/hystrix-javanica/build.gradle
=> apply osgi gradle plugin so the we can use javanica in a OSGi Enviroment

hystrix-core/src/jmh/java/com/netflix/hystrix/perf/CollapserPerfTest.java, hystrix-core/src/jmh/java/com/netflix/hystrix/perf/ObservableCollapserPerfTest.java
=> Add jmh collapser benchmarks

hystrix-core/src/jmh/java/com/netflix/hystrix/perf/CollapserPerfTest.java, hystrix-core/src/jmh/java/com/netflix/hystrix/perf/ObservableCollapserPerfTest.java
Addresses #882 in master (Merge of #883 from 1.4.x)
=> JMH benchmarks for collapsers in master

hystrix-core/src/jmh/java/com/netflix/hystrix/perf/ObservableCollapserPerfTest.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixCollapser.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixObservableCollapser.java, hystrix-core/src/main/java/com/netflix/hystrix/collapser/CollapsedRequestObservableFunction.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCollapserTest.java
Merge into master of #890.  Addresses #865
=> Allow multiple values per request-arg in a HystrixObservableCollapser

hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCollapserTest.java
=> Update unit tests for HystrixObservableCollapser to check HystrixRequestContext

hystrix-examples/src/main/java/com/netflix/hystrix/examples/basic/ObservableCollapserGetWordForNumber.java, hystrix-examples/src/main/java/com/netflix/hystrix/examples/basic/ObservableCommandNumbersToWords.java
=> Forward port hystrix observable collapser example (#905)

hystrix-contrib/hystrix-servo-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisherAbstract.java, hystrix-contrib/hystrix-servo-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisherCommand.java, hystrix-contrib/hystrix-servo-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisherCommandAbstract.java
=> Adding a layer of abstraction to Servo integration for Hystrix command metrics that doesn't assume a specific implementation

hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
This is a forward port of #911 
New unit tests based on the question at: https://groups.google.com/forum/#!topic/hystrixoss/XgAuwe2RxS8
=> Unit tests around large threadpool/small queue scenario

build.gradle, gradle/wrapper/gradle-wrapper.properties
Addresses #730.
h/t to @jkschneider for the solution
=> Fix generated pom

hystrix-contrib/hystrix-javanica/README.md, hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/aop/aspectj/HystrixCommandAspect.java, hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/AbstractHystrixCommandFactory.java, hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/BatchHystrixCommand.java, hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/CommandAction.java, hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/CommandExecutionAction.java, hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/CommandExecutor.java, hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/GenericCommand.java, hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/LazyCommandExecutionAction.java, hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/MetaHolder.java, hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/MethodExecutionAction.java, hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/exception/FallbackDefinitionException.java, hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/utils/FallbackMethod.java, hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/utils/FutureDecorator.java, hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/utils/MethodProvider.java, hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/collapser/BasicCollapserTest.java, hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/domain/Domain.java, hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/domain/User.java, hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/fallback/BasicCommandFallbackTest.java
=> Javanica iss 929

build.gradle
=> Mark servlet-api as 'provided' in generated POMs

hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCollapserTest.java
Some runs in #955 showed there might still be a bug
=> Reinstate the HystrixObservableCollapserTest stress test 

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
=> Prevent execution of run method when an onXXXStart hook throws an exception

build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Added Cobertura plugin

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java
=> Added AbstractCommand.getExecutionException to solve #998

hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandProperties.java
Fix a comment which is a bit confusing
=> Fix a comment which is a bit confusing

build.gradle, hystrix-dashboard/src/main/webapp/components/hystrixCommand/hystrixCommand.js
=> Removed dashboard references to latencyTotal_mean

hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixRequestContext.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixCollapserTest.java
now we can leverage try-with-resources on java 7 and forward
=> Made HystrixRequestContext Closeable

hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixRequestContext.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixCollapserTest.java
Backport of #1111 .  Thanks @velo !
=> Backport #1111 to 1.4.x

hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCommandTest.java, hystrix-core/src/test/java/com/netflix/hystrix/TestableExecutionHook.java
Also, removed some assertions that were not working under concurrent test runs
=> Made errors in hook unit tests easier to debug

hystrix-core/src/test/java/com/netflix/hystrix/metric/consumer/HealthCountsStreamTest.java
to make sure rejections happen as expected
=> Increasing time spent in commands in HealthCountsStreamTest 

hystrix-core/src/main/java/com/netflix/hystrix/metric/CachedValuesHistogram.java, hystrix-core/src/main/java/com/netflix/hystrix/metric/consumer/RollingDistributionStream.java
This allows us to release the Histogram object earlier.  Only the single thread doing the calculations accesses the object
=> Do all calculation of histogram values upfront.

hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixRequestContext.java
=> Add AutoCloseable interface to HystrixRequestContext

CHANGELOG.md, hystrix-contrib/hystrix-javanica/build.gradle, hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/BasicHystrixTest.java, hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/cache/BasicCacheTest.java, hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/collapser/BasicCollapserTest.java, hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/command/BasicCommandTest.java, hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/configuration/collapser/BasicCollapserPropertiesTest.java, hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/configuration/command/BasicCommandPropertiesTest.java, hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/error/BasicErrorPropagationTest.java, hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/fallback/BasicCommandFallbackTest.java, hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/observable/BasicObservableTest.java, hystrix-contrib/hystrix-junit/src/main/java/com/hystrix/junit/HystrixRequestContextRule.java
Forward port of #1184 to 2.0.x
=> migrating all hystrix-javanica tests to hystrix-junit

hystrix-contrib/hystrix-servo-metrics-publisher/build.gradle
=> Upgrade Servo to 0.12.4

hystrix-contrib/hystrix-servo-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/servopublisher/HystrixServoMetricsPublisherCommand.java
=> Modify Servo tag "type" -> "class" and "instance" -> "id"

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixCachedObservable.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixCollapser.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandResponseFromCache.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixObservableCollapser.java, hystrix-core/src/main/java/com/netflix/hystrix/collapser/CollapsedRequestSubject.java, hystrix-core/src/main/java/com/netflix/hystrix/collapser/HystrixCollapserBridge.java, hystrix-core/src/main/java/com/netflix/hystrix/collapser/RequestBatch.java, hystrix-core/src/main/java/com/netflix/hystrix/collapser/RequestCollapser.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixCollapserTest.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixObservableCollapserTest.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixRequestCacheTest.java, hystrix-core/src/test/java/com/netflix/hystrix/collapser/CollapsedRequestSubjectTest.java
Similar to #1204, but for collapsers
=> Wired up unsubscription for HystrixCollapsers and HystrixObservableCollapsers

hystrix-core/src/main/java/com/netflix/hystrix/collapser/RequestCollapserFactory.java
=> remove dead field defaultNameCache

hystrix-core/src/main/java/com/netflix/hystrix/HystrixObservableCollapser.java
=> Moved all work performed in HystrixObservableCommand.toObservable inside an Observable.defer to make it lazy

hystrix-contrib/hystrix-javanica/README.md
=> Spell correction.

hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommand.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommandProperties.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandPropertiesTest.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
I think the #1265 PR was missing a couple changes from master.  This applies #1265 on top of tip-of-master.
=> Evaluate pr 1265

hystrix-core/src/main/java/com/netflix/hystrix/metric/consumer/BucketedCumulativeCounterStream.java, hystrix-core/src/main/java/com/netflix/hystrix/metric/consumer/BucketedRollingCounterStream.java, hystrix-core/src/main/java/com/netflix/hystrix/metric/consumer/RollingConcurrencyStream.java, hystrix-core/src/main/java/com/netflix/hystrix/metric/consumer/RollingDistributionStream.java, hystrix-core/src/test/java/com/netflix/hystrix/metric/consumer/HealthCountsStreamTest.java
Then the work happens only once and all subscribers get that copy
=> Make sure that metrics streams are multicast 

hystrix-contrib/hystrix-javanica/build.gradle, hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/utils/FallbackMethod.java, hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/utils/TypeHelper.java, hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/fallback/BasicGenericFallbackTest.java, hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/spring/fallback/GenericFallbackTest.java
https://github.com/Netflix/Hystrix/issues/1328
cc @mattrjacobs / @VaultB0Y
=> iss1328: fix

hystrix-core/build.gradle
It'd be nice to upgrade JMH to the latest version. :)
=> Bump JMH to the latest version(1.15)

build.gradle
Let's upgrade JMH plugin as well if it's okay :)
ref. https://plugins.gradle.org/plugin/me.champeau.gradle.jmh
ref. https://github.com/Netflix/Hystrix/pull/1382
=> Bump JMH gradle plugin to the latest version(0.3.1)

hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/utils/EnvUtils.java
Performance improvement in EnvUtils. Read "weavingMode" system property only one time.
=> iss:1387: Performance improvement in EnvUtils. Read "weavingMode" system property only one time.

hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java, hystrix-core/src/test/java/com/netflix/hystrix/CommonHystrixCommandTests.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixCommandTest.java
=> If command is unsubscribed before any work starts, just return Observable.never()

hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/sample/stream/HystrixConfigurationJsonStream.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPool.java, hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPoolProperties.java, hystrix-core/src/main/java/com/netflix/hystrix/config/HystrixThreadPoolConfiguration.java, hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixConcurrencyStrategy.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixThreadPoolPropertiesTest.java, hystrix-core/src/test/java/com/netflix/hystrix/HystrixThreadPoolTest.java, hystrix-serialization/src/main/java/com/netflix/hystrix/serial/SerialHystrixConfiguration.java
=> Add property to control maximum thread pool size

hystrix-core/src/main/java/com/netflix/hystrix/util/HystrixRollingPercentile.java
=> Clear the percentile snapshot whenever all buckets get cleared

hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPoolProperties.java
Fix a little spell mistake in comments, "-1 turns if off" should be "-1 turns it off".
=> Fix a little spell mistake in comments.

hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/sample/stream/HystrixSampleSseServlet.java
…mpling stream
Thanks @mattnelson for https://github.com/Netflix/Hystrix/pull/1442#discussion_r92509354
=> Optimize server thread exit

README.md, hystrix-contrib/hystrix-servo-metrics-publisher/build.gradle
=> Upgrade servo to 0.10.1

hystrix-contrib/hystrix-codahale-metrics-publisher/build.gradle
codahale metrics-core 3.3.2 http://metrics.dropwizard.io/3.2.2/about/release-notes.html
=> Updating codahale metrics-core to 3.2.2

hystrix-core/src/main/java/com/netflix/hystrix/metric/consumer/HealthCountsStream.java
=> Move HealthCountsStream subscribe outside synchronized block

hystrix-dashboard/src/main/webapp/components/hystrixCommand/templates/hystrixCircuit.html
=> Fixed incorrect color of circuit status in dashboard

hystrix-core/src/main/java/com/netflix/hystrix/metric/CachedValuesHistogram.java
=> Fix to permyriad calculation

hystrix-contrib/hystrix-codahale-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisherThreadPool.java
=> Fix incorrect return value in CodaHale metrics publisher of threadpool config

hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/conf/HystrixPropertiesManager.java, hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/configuration/command/BasicCommandPropertiesTest.java
=> Added Javanica support for setting allowMaximumSizeToDivergeFromCoreSize in an annotation

hystrix-core/src/test/java/com/netflix/hystrix/UnsubscribedTasksRequestCacheTest.java
The test execution was non-deterministic due to the executor service with two threads. This was executing the runnables with essentially random order and timing. The runnables are now executed one after the other on a single thread, which still allows to test the caching behaviour.
=> Stabilize another test

hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/sample/stream/HystrixSampleSseServlet.java, hystrix-contrib/hystrix-metrics-event-stream/src/test/java/com/netflix/hystrix/contrib/sample/stream/HystrixSampleSseServletTest.java
Referencing issue: https://github.com/Netflix/Hystrix/issues/1756
=> Fix race condition in HystrixSampleSseServlet for response writes

README.md
```diff
- futher
+ further
```
=> Fix: Minor typo mistake

README.md
=> Fix image reference
